# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Klipa < Formula
  desc "A CLI clipboard manager for saving and retrieving text from your clipboard."
  homepage "https://github.com/Humiditii/klipa"
  version "1.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Humiditii/klipa/releases/download/v1.0.1/klipa_1.0.1_darwin_amd64.tar.gz"
      sha256 "08ac2d7af1953b5555bdaedc7ef81defe8afd9ed04d9711c64a6bf2bf0a171be"

      def install
        bin.install "klipa"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Humiditii/klipa/releases/download/v1.0.1/klipa_1.0.1_darwin_arm64.tar.gz"
      sha256 "94214b9b5b36c27cdb01fcdf3eff0252c9ff07dbce8a26f2ce147ab1e6447620"

      def install
        bin.install "klipa"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/Humiditii/klipa/releases/download/v1.0.1/klipa_1.0.1_linux_amd64.tar.gz"
      sha256 "13a10cd6aa0881e4827818c3b20625305194035f5e5a99bd3af4b8d0a101f4b0"
      def install
        bin.install "klipa"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/Humiditii/klipa/releases/download/v1.0.1/klipa_1.0.1_linux_arm64.tar.gz"
      sha256 "f06db2025376991c6bedf608a73b66d9a044ad6f71f1eea87955daf54c3cb9d6"
      def install
        bin.install "klipa"
      end
    end
  end

  test do
    system "#{bin}/klipa", "--help"
  end
end
