# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Klipa < Formula
  desc "A CLI clipboard manager for saving and retrieving text from your clipboard."
  homepage "https://github.com/Humiditii/klipa"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Humiditii/klipa/releases/download/v1.0.0/klipa_1.0.0_darwin_amd64.tar.gz"
      sha256 "824f3e88bad06415de2fffb7fab44dadd2bb10eeaf1a88953086fad76d5ecfea"

      def install
        bin.install "klipa"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Humiditii/klipa/releases/download/v1.0.0/klipa_1.0.0_darwin_arm64.tar.gz"
      sha256 "e4d27e3451aa7916ba99b28ece4d7bc52e7176a8910bc8e36c5cab50228702c5"

      def install
        bin.install "klipa"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/Humiditii/klipa/releases/download/v1.0.0/klipa_1.0.0_linux_amd64.tar.gz"
      sha256 "00fb0ab75220b6528ce3158fd13c3609e071289177127376d7793bf9cecc49cb"
      def install
        bin.install "klipa"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/Humiditii/klipa/releases/download/v1.0.0/klipa_1.0.0_linux_arm64.tar.gz"
      sha256 "46bd94be5596029889a6b3516010b8018797a099121f2fb1ad6176d0ed86890f"
      def install
        bin.install "klipa"
      end
    end
  end

  test do
    system "#{bin}/klipa", "--help"
  end
end
